name: 'Check copyright'
description: 'Checking for missing copyright headers'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Check copyright header in every .java, .kts and .kt file
      shell: bash
      run: |
        LIST=$(find . -type f \( -name "*.java" -o -name "*.kt" -o -name "*.kts" \) -exec grep -HL 'Copyright 20.. Budapest University of Technology and Economics' '{}' ';')
        [ -z "$LIST" ] && echo "Copyright OK" || printf "Copyright notice not present in files:\n$LIST\n"
        [ -z "$LIST" ]