name: 'Gradle build action'
description: 'Running gradle build without tests'
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Setup java 17
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
      with:
        distribution: temurin
        java-version: 17
    - name: build gradle
      uses: ./.github/actions/cache-build
      with:
        arguments: test

    - name: Badge name generation
      if: ${{ always() }}
      id: name
      shell: bash
      run: |
        echo "name=test-${{ runner.os }}" >> $GITHUB_OUTPUT 
        echo "label=${{ runner.os }} test" >> $GITHUB_OUTPUT 
    - name: Positive outcome badge
      uses: RubbaBoy/BYOB@27b128c2a65c3b64184f44d2249d0882391b1767
      with:
        NAME: ${{ steps.name.outputs.name }}
        LABEL: ${{ steps.name.outputs.label }}
        STATUS: Success
        COLOR: green
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Negative outcome badge
      if: ${{ failure() }}
      uses: RubbaBoy/BYOB@27b128c2a65c3b64184f44d2249d0882391b1767
      with:
        NAME: ${{ steps.name.outputs.name }}
        LABEL: ${{ steps.name.outputs.label }}
        STATUS: Failure
        COLOR: red
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}