name: 'Gradle build action'
description: 'Running gradle build without tests'
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Setup java 17
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
      with:
        distribution: temurin
        java-version: 17
    - name: build gradle
      uses: ./.github/actions/cache-build
      with:
        arguments: test

    - name: Badge name generation
      if: ${{ always() }}
      id: name
      shell: bash
      run: |
        export folder=badges/build-${{ runner.os }}
        mkdir -p $folder
        echo "folder=$folder" >> $GITHUB_OUTPUT 
        echo "name=$folder/badge.svg" >> $GITHUB_OUTPUT 
        echo "label=${{ runner.os }} test" >> $GITHUB_OUTPUT 
    - name: Positive outcome badge
      uses: emibcn/badge-action@v2.0.2
      with:
        label: ${{ steps.name.outputs.label }}
        status: Success
        color: 'green'
        path: ${{ steps.name.outputs.name }}
    - name: Negative outcome badge
      if: ${{ failure() }}
      uses: emibcn/badge-action@v2.0.2
      with:
        label: ${{ steps.name.outputs.label }}
        status: Failure
        color: 'red'
        path: ${{ steps.name.outputs.name }}
    - name: setup rsync for windows
      if: runner.os == 'Windows'
      uses: GuillaumeFalourd/setup-rsync@v1.1
    - name: Deploy badges
      if: github.ref == 'refs/heads/master'
      if: ${{ always() }}
      uses: JamesIves/github-pages-deploy-action@132898c54c57c7cc6b80eb3a89968de8fc283505 # v3.7.1
      with:
        branch: badges
        folder: ${{ steps.name.outputs.folder }}
        target_folder: ${{ steps.name.outputs.folder }}
        single_commit: true