name: 'Deploy docs'
description: 'Deploying docs to /wiki'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: pip install mkdocs-material==8.3.9
      shell: bash
    - run: pip install python-markdown-math==0.8
      shell: bash
    - run: pip install mkdocs==1.3.0
      shell: bash
    - run: mkdocs build --site-dir wiki
      shell: bash
      working-directory: doc/wiki
    - uses: JamesIves/github-pages-deploy-action@132898c54c57c7cc6b80eb3a89968de8fc283505 # v3.7.1
      with:
        branch: gh-pages
        folder: doc/wiki/wiki
        target_folder: wiki