name: CI-docs

on:
  push:
    branches:
      - master
      - docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material=8.3.9
      - run: pip install python-markdown-math==0.8
      - run: pip install mkdocs==1.3.0
      - run: mkdocs gh-deploy --site-dir wiki
        working-directory: doc/wiki
