name: macOS build and test
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

permissions: write-all

jobs:
  test-mac:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-13, macos-12, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: macOS library hack
        run: |
          cp lib/*dylib ./
          cp lib/*jnilib ./
          cp libmpfr.dylib libmpfr.4.dylib
          cp libmpfr_java-1.4.jnilib libmpfr_java.jnilib
          sudo ln -sf $PWD/libmpfr.4.dylib /usr/local/lib/
          for i in subprojects/*/*; do cp *dylib $i/; done
          for i in subprojects/*/*; do cp *jnilib $i/; done
      - name: Build
        uses: ./.github/actions/build-action
      - name: Positive outcome badge
        if: ${{ matrix.os == 'macos-latest' }}
        uses: ./.github/actions/badge-creation
        with:
          label: "${{ runner.os }} build"
          status: "Success"
          color: "green"
          path: "badges/build-${{ runner.os }}"
      - name: Negative outcome badge
        if: ${{ failure() && matrix.os == 'macos-latest' }}
        uses: ./.github/actions/badge-creation
        with:
          label: "${{ runner.os }} build"
          status: "Failure"
          color: "red"
          path: "badges/build-${{ runner.os }}"
      - name: Run tests
        uses: ./.github/actions/test-action
      - name: Positive outcome badge
        if: ${{ matrix.os == 'macos-latest' }}
        uses: ./.github/actions/badge-creation
        with:
          label: "${{ runner.os }} test"
          status: "Success"
          color: "green"
          path: "badges/test-${{ runner.os }}"
      - name: Negative outcome badge
        if: ${{ failure() && matrix.os == 'macos-latest' }}
        uses: ./.github/actions/badge-creation
        with:
          label: "${{ runner.os }} test"
          status: "Failure"
          color: "red"
          path: "badges/test-${{ runner.os }}"
