name: CI/CD job orchestration
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  workflow_call:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Build
        uses: ./.github/actions/build-action
  
  javadoc: # deploys to GH pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Deploy javadoc to github-pages
        uses: ./.github/actions/deploy-javadoc

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Run tests, submit coverage report to codacy
        uses: ./.github/actions/test-action