name: CI/CD job orchestration
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  workflow_call:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Build
        uses: ./.github/actions/build-action
  
  javadoc: # deploys to GH pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Deploy javadoc to github-pages
        uses: ./.github/actions/deploy-javadoc

  test-linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]
    needs: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Run tests, submit coverage report to codacy
        uses: ./.github/actions/test-action
      - name: Send test coverage to Codacy
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java $(find '**/jacoco*.xml' -printf '-r %p ')
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

  test-windows:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-2019, windows-2022]
    needs: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Install VC-Redist 2010 and 2012
        run: |
          Install-Module -Name VcRedist -Force
          $VcList = Get-VcList -Export All | Where-Object { $_.Release -eq "2010" -or $_.Release -eq "2012" }
          Save-VcRedist -VcList $VcList
          Install-VcRedist -VcList $VcList -Silent
      - name: Run tests, submit coverage report to codacy
        uses: ./.github/actions/test-action

  