
name: Reformat code
on: 
  workflow_dispatch:
    inputs:
      file_mask:
        description: 'File mask to reformat'
        required: true
        default: 'subprojects/*.java'

jobs:
  reformat:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Permission fix
      run: sudo chown -R $(whoami) .
    - name: Do reformat
      uses: leventeBajczi/intellij-idea-format@v0.1.1
      with:
        settings-file: "./doc/ThetaIntelliJCodeStyle.xml"
        file-mask: ${{ inputs.file_mask }}
      
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Reformatted code"
